### ISSUE TITLE
api层接口识别不了

### ISSUE THREAD

**Issue by junziqiao** [houxinlin/cool-request#1]
@RequestMapping("/sys/user")
public interface SysUserApi {

    @RequestMapping("/addUser")
    public String addUser(UserReq req);
}

**Comment by junziqiao** [comment]
api层接口识别不了

**Comment by houxinlin** [comment]
> @RequestMapping（“/sys/user”） 公共接口SysUserApi {
> 
> ```
> @RequestMapping("/addUser")
> public String addUser(UserReq req);
> ```
> 
> }
是的，试试动态刷新技术

**Comment by houxinlin** [comment]
> @RequestMapping("/sys/user") public interface SysUserApi {
> 
> ```
> @RequestMapping("/addUser")
> public String addUser(UserReq req);
> ```
> 
> }

是的，试试动态刷新技术
