### ISSUE TITLE
xxl-job定时任务识别不到

### ISSUE THREAD

**Issue by muzizi727** [houxinlin/cool-request#102]
IntelliJ IDEA 2024.1
cool request：v2024.8.15
更新之后定时任务都没了

**Comment by houxinlin** [comment]
功能由call this method代替

**Comment by lgg476864889** [comment]
> 功能由call this method代替

xxl-job的参数没有办法通过这个写入了

**Comment by houxinlin** [comment]
怎么提到这了，call this method有脚本，在脚本里，用xxl-job的api去给他的ThreadLocal设置参数就行

![Image](https://github.com/user-attachments/assets/f2758680-3f78-445a-b232-1d99b0a70fc5)

**Comment by houxinlin** [comment]
是的，这个在官网的确没有说明，后续补充，您有兴趣也可以提pr,
