### ISSUE TITLE
常量+路径用插件可以搜到吗？

### ISSUE THREAD

**Issue by BJPotter** [houxinlin/cool-request#106]
目前公司的项目controller都前缀一般都是常量，例如：URL.V3=/v3/openapi
@GetMapping(URL.V3+"/users"),由于前缀有好多个可能还有@GetMapping(URL.V4+"/users")，@GetMapping(URL.V5+"/users")导致无法通过插件定位到想要的接口，希望能够支持，目前插件在IDEA2024.1是搜不到的

**Comment by houxinlin** [comment]
可以搜到啊，你是不用错插件了
![image](https://github.com/user-attachments/assets/1d01203f-8ac7-405b-8d00-7902eb89703b)
