### ISSUE TITLE
新版设置全局cookie不生效

### ISSUE THREAD

**Issue by shihuangzhuizhu** [houxinlin/cool-request#107]
点击右上角Cookie，导入JSESSIONID=xxxxx，点击Add domain，点击保存ok，请求接口cookie未生效。之前版本可以，今天升级之后操作不行了，是操作问题吗？

**Comment by houxinlin** [comment]
刚测试了下，新版加入的bug ，add domain的时候，前面要加上http或者https

**Comment by shihuangzhuizhu** [comment]
能发个图给我参考下具体怎么配置吗？

**Comment by shihuangzhuizhu** [comment]
> 刚测试了下，新版加入的bug ，add domain的时候，前面要加上http或者https

能发个图给我参考下怎么配置吗？

**Comment by houxinlin** [comment]
![image](https://github.com/user-attachments/assets/71238738-7ea7-4657-b0ff-2b89be6d4fcb)

手动加http，自动从响应里面提取应该没问题，尽量不要手动添加

**Comment by shihuangzhuizhu** [comment]
> ![image](https://private-user-images.githubusercontent.com/38684327/366816576-71238738-7ea7-4657-b0ff-2b89be6d4fcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzQ2OTQsIm5iZiI6MTcyNjEzNDM5NCwicGF0aCI6Ii8zODY4NDMyNy8zNjY4MTY1NzYtNzEyMzg3MzgtN2VhNy00NjU3LWIwZmYtMmI4OWJlNmQ0ZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA5NDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDc1ZWRiN2JjZGM1OWMxYjg0NjU5MzQxZDkzMmIzNDFmOWNkNDE3ZWY4YjVjYjUxZDNiNjZlZmQ0OTBlZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xX_Npl2YpHDofLTvuiTM50NArU1YMo1XrZ6Dw6JntsQ)
> 
> 手动加http，自动从响应里面提取应该没问题，尽量不要手动添加

点击Add Cookie, 添加了对应的cookie信息，如Cookie_36=JSESSIONID=xxxxx;path=/api，cookie还是不生效

**Comment by houxinlin** [comment]
Cookie_36是key，JSESSIONID也是key，key=key=value?

**Comment by shihuangzhuizhu** [comment]
> Cookie_36是key，JSESSIONID也是key，key=key=value?

若value里面有=符号，是不是有问题，比如key=Cookie,value=JSESSIONID=xxxx

**Comment by houxinlin** [comment]
你这样web容器肯定识别不了，请求发送的没错，直接写JSESSIONID=xxxxx;path=/api试试

**Comment by houxinlin** [comment]
新版发布，可在idea仓库更新
