### ISSUE TITLE
request/response执行脚本发起http请求，设置origin请求头不生效

### ISSUE THREAD

**Issue by c913647576** [houxinlin/cool-request#111]
我在request(前置脚本)/response(后置脚本)中执行脚本请求token接口获取token，在请求头中添加 Origin 后，服务端获取这个请求头，结果是null，脚本代码拿出来单独执行请求则没这个问题，其他请求头(如user-agent)也没这个问题；其中使用的http工具是hutool里的HttpRequest。

**Comment by houxinlin** [comment]
加群，发下代码
