### ISSUE TITLE
测试工具无法同时支持@RequestParam,@RequestPart两个注解的复杂参数

### ISSUE THREAD

**Issue by XiaoSong2017** [houxinlin/cool-request#112]
![image](https://github.com/user-attachments/assets/23fe2781-a3d9-413e-a05b-1111619a84c2)
![image](https://github.com/user-attachments/assets/87c84a32-b99b-4de5-aa18-9c78b8165be7)
建议后续可以优化一下

**Comment by houxinlin** [comment]
好

**Comment by XiaoSong2017** [comment]
> 支持的，api上是不是有consumes或者produces，删了看看
![image](https://github.com/user-attachments/assets/54bb4ace-22ad-4096-9955-6fdb6d8ecce1)
接口上并没有额外设置consumes和produces,感觉应该是用postman可以进一步自定义设置内容类型的缘故,建议这个工具也可以考虑支持下

**Comment by houxinlin** [comment]
我在排查下

**Comment by houxinlin** [comment]
我试了下可以的啊，有代理工具吗，在cool request设置下代理，抓个包看看最终的发送报文是啥
![image](https://github.com/user-attachments/assets/7eab550b-d88e-45e5-9c7c-b1bca9785f9d)
