### ISSUE TITLE
抽象controller实现,扫描不到

### ISSUE THREAD

**Issue by newbirdking** [houxinlin/cool-request#113]
定义一个抽象的controller类,其余实现该方法,查询的时候查不到改方法
![image](https://github.com/user-attachments/assets/a1b66ad0-bac7-4541-975a-c8de679486ff)

![image](https://github.com/user-attachments/assets/71a655ea-daee-4dca-a127-4d66f3acbbce)

**Comment by houxinlin** [comment]
你用的搜索不是我的，我的插件叫Cool Request
