### ISSUE TITLE
希望能增加自定义RMI接口的设置

### ISSUE THREAD

**Issue by zxfxpower** [houxinlin/cool-request#114]
如题

**Comment by zxfxpower** [comment]
@houxinlin REFLEX请求报错：java.lang.IllegalArgumentException: Not Found RMI Port，我看了下源码com.cool.request.components.http.net.ReflexRequestCallMethod#invoke 好像无法正确获取到rmi端口
我们的项目使用的是spring mvc，部署在tomcat中，RMI端口默认是1099。是不是这种情况不支持

**Comment by houxinlin** [comment]
和这个rmi没有关系，现在只支持springboot

**Comment by zxfxpower** [comment]
@houxinlin 了解，谢谢解答
