### ISSUE TITLE
cookie设置了JSESSIONID没有生效

### ISSUE THREAD

**Issue by maodouzi123** [houxinlin/cool-request#117]
版本2024.10.15
domain设置的是http://localhost:8888，cookie设置是：JSESSIONID=51DBAFC35A52DDE38AD83D496D47D3E0; Path=/; HttpOnly

**Comment by houxinlin** [comment]
是个bug，感谢提出，domain写成localhost，不要带端口号和http，可以临时解决一下，获取加我微信，发修复后的版本

**Comment by houxinlin** [comment]
有全局环境变量，也可以设置一个环境，请求头中增加

**Comment by maodouzi123** [comment]
还是不行，设置了全局变量，domain写成localhost都不行，后台看sessionid拿到的值不是我设置的值

**Comment by houxinlin** [comment]
加个wx把

**Comment by maodouzi123** [comment]
好像可以了。。。
