### ISSUE TITLE
更新到2024.11.1版本后,老版本springboot无法运行, 一直报错

### ISSUE THREAD

**Issue by 643403859** [houxinlin/cool-request#118]
![1730376233171](https://github.com/user-attachments/assets/4b3df35b-a31f-4f39-9fe2-71cbe04852a2)
项目比较老,使用springboot1.4,升级插件后项目无法启动, 卸载后正常.回退到2024.8.15版本也正常使用

**Comment by houxinlin** [comment]
等待一下

**Comment by houxinlin** [comment]
新版修复了
