### ISSUE TITLE
接口导出到ApiPost8

### ISSUE THREAD

**Issue by BaoHao-JIA** [houxinlin/cool-request#121]
按照ApiPost官网教程更换了Host配置，提示还是如下显示网络失败，是未兼容ApiPost8的版本还是缺少配置的原因
![image](https://github.com/user-attachments/assets/8b32ad0f-f84b-4141-a4d3-63086d3b4625)

**Comment by houxinlin** [comment]
ApiPost8不兼容

**Comment by BaoHao-JIA** [comment]
apipost现在只能兼容到7的版本，8的版本后续有考虑兼容吗

**Comment by houxinlin** [comment]
暂时不考虑，他们自己有插件可以导出

**Comment by BaoHao-JIA** [comment]
好的，谢谢
