### ISSUE TITLE
下载Zip形式的插件报病毒

### ISSUE THREAD

**Issue by RyuAsuka** [houxinlin/cool-request#122]
![image](https://github.com/user-attachments/assets/056bf432-a427-4b5e-9b18-66e6ad9514f0)

这个是准备导入到公司的电脑上用的，公司电脑在内网，与互联网不连通，因此只能通过这种方式手动安装。由于公司电脑有较强的网络安全策略，下载到自己笔记本上报病毒，上传到公司电脑后也报病毒，不敢安装了

**Comment by houxinlin** [comment]
这是因为内置了frp的内网穿透，frp会被杀毒软件报毒,放心安装，https://github.com/fatedier/frp

**Comment by houxinlin** [comment]
新版移除了，升级下
