### ISSUE TITLE
中文参数乱码

### ISSUE THREAD

**Issue by xgx-legion** [houxinlin/cool-request#13]
![微信截图_20240229100448](https://github.com/houxinlin/cool-request/assets/30016964/74a36868-2971-4f31-a988-7aff4f0371c5)

**Comment by houxinlin** [comment]
不要使用反射请求也是乱码吗？

**Comment by houxinlin** [comment]
> > > > 不要使用反射请求也是乱码吗？
> > > 
> > > 
> > > http是正常的没有乱码
> > 
> > 
> > 可能话idea环境有关系，我想办法复现一下，能提供一下你的idea版本，还有项目的jdk版本吗
> 
> IntelliJ IDEA 2021.3.3 Build #IU-213.7172.25 jdk1.8.0_131 UTF-8

目前复现不了，插件中有联系方式，可以加个v详细沟通下吗
