### ISSUE TITLE
建议增加gson支持

### ISSUE THREAD

**Issue by Kur1ko** [houxinlin/cool-request#130]
JacksonFieldAnnotationDescription里支持了JsonProperty获取序列化属性，建议把gson的方式也加上呗。
// 支持gson方式
        PsiAnnotation gsonAnnotation = AnnotationUtil
                .findAnnotation(field, "com.google.gson.annotations.SerializedName");
        if (gsonAnnotation != null) {
            String value = ParamUtils.getAnnotationStringValue(gsonAnnotation, "value");
            if (value != null) return value;
        }
解析value时ParamUtils增加
if (psiAnnotationMemberValue instanceof PsiLiteralExpression) {
            Object propertyValue = ((PsiLiteralExpression) psiAnnotationMemberValue).getValue();
            if (propertyValue instanceof String) return List.of(propertyValue.toString());
        }

我看idea插件已经升到2024.8.1的版本了。但是这边分支好像没有这个版本。就不提交pr了

**Comment by houxinlin** [comment]
可以，如果有兴趣开发可以联系我

**Comment by houxinlin** [comment]
最新版是2024.12.1, 按日期走得，idea版本太低只能按2024.8.1,我看了下新版是支持gson得

**Comment by Kur1ko** [comment]
> 最新版是2024.12.1, 按日期走得，idea版本太低只能按2024.8.1,我看了下新版是支持gson得

那就对了。。我版本比较低，是2021.1.3的，只更新的到2024.8.1版本的😅
