### ISSUE TITLE
搜索接口可否增加快捷键

### ISSUE THREAD

**Issue by wxyShine** [houxinlin/cool-request#14]
比如 alt+F

**Comment by houxinlin** [comment]
可以，需求已提上日程

**Comment by ayuayue** [comment]
可以临时 双击 shift 在默认的 anysearch 中切换到最后的 api search tab查看

**Comment by wxyShine** [comment]
> 可以临时 双击 shift 在默认的 anysearch 中切换到最后的 api search tab查看

`在默认的 anysearch 中切换到最后的 api search tab` 这一步有快捷么

**Comment by houxinlin** [comment]
新版已增加

**Comment by wxyShine** [comment]
> 新版已增加

和[翻译插件](https://plugins.jetbrains.com/plugin/8579-translation) 冲突了好像 ,  alt+F 应该不冲突 之前[这个]
(https://plugins.jetbrains.com/plugin/16988-fast-request--api-buddy)插件就是alt+F
