### ISSUE TITLE
json格式响应中缺少null值key

### ISSUE THREAD

**Issue by weidong0915** [houxinlin/cool-request#19]
当接口响应数据为json格式时,界面中{}选项中的数据会忽略掉值为null的数据,这会影响开发人员对相应数据的判断, 希望取消此忽略
![image](https://github.com/houxinlin/cool-request/assets/35517927/f55b9b79-8e33-43de-a04c-22d924ba97a2)
![image](https://github.com/houxinlin/cool-request/assets/35517927/6af37b09-37d9-4d17-90d3-312bffc03c09)

**Comment by houxinlin** [comment]
这是个问题，感谢提醒

**Comment by houxinlin** [comment]
以修复
