### ISSUE TITLE
定时任务手动触发

### ISSUE THREAD

**Issue by weidong0915** [houxinlin/cool-request#22]
![image](https://github.com/houxinlin/cool-request/assets/35517927/fea79190-fda0-417a-a09e-1471ac27efdb)

这个是什么原因有碰到么, 项目启动了, 定时任务手动触发不了

**Comment by houxinlin** [comment]
可以加个联系方式吗

**Comment by ribongan** [comment]
同样也是项目启动了，手动触发时还是提示只支持项目启动时调用

**Comment by houxinlin** [comment]
> 同样也是项目启动了，手动触发时还是提示只支持项目启动时调用

加一下我v

**Comment by hzl7652** [comment]
我也遇上相同的问题，多模块项目，定时在子模块中。主项目启动后，触发定时器，也报错
![image](https://github.com/houxinlin/cool-request/assets/1568008/a6eff7df-3fe4-40fb-885b-eb457fa09c5d)

**Comment by houxinlin** [comment]
> 我也遇上相同的问题，多模块项目，定时在子模块中。主项目启动后，触发定时器，也报错 ![image](https://private-user-images.githubusercontent.com/1568008/317173020-a6eff7df-3fe4-40fb-885b-eb457fa09c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjU5NDMsIm5iZiI6MTcxMTUyNTY0MywicGF0aCI6Ii8xNTY4MDA4LzMxNzE3MzAyMC1hNmVmZjdkZi0zZmU0LTQwZmItODg1Yi1lYjQ1N2ZhMDljNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDc0NzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNkMmQ4NmIzNDE2NDhlZDFkODUyZTZlMTdlODU2N2JmNjdmNWUzYzYxOWNiZDU4MTM1ZDJlNTBlYzExOGVmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bdt_OySwKDYy4Yq1k8LqXWLYc7Qk-mOSHwMOJMk-ZUw)

主页有群，加一下，发你一个内测版本，在试试
