### ISSUE TITLE
增加右键复制API路径

### ISSUE THREAD

**Issue by Sdky** [houxinlin/cool-request#31]
希望能在方法右键增加复制 API 路径的快捷操作，类似下图这样：

![2024-03-15_20-44-49](https://github.com/houxinlin/cool-request/assets/29597396/a8d8c245-ce50-4377-b356-325c2fb663a5)

**Comment by houxinlin** [comment]
目前可以在窗口中右击api，选择复制

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载
