### ISSUE TITLE
不能监听到程序的端口

### ISSUE THREAD

**Issue by roukaixin** [houxinlin/cool-request#35]
![端口](https://github.com/houxinlin/cool-request/assets/47386021/0fd6cfc7-4dad-43e6-9e9f-9e27d7401999)

项目是启动状态也不能监听到端口

**Comment by houxinlin** [comment]
能看看在配置文件中是怎么定义端口的吗

**Comment by roukaixin** [comment]
> 能看看在配置文件中是怎么定义端口的吗

![端口1](https://github.com/houxinlin/cool-request/assets/47386021/1fa1c844-95cf-48c6-aaaa-c8ebbee5b97f)

就是正常的配置

**Comment by houxinlin** [comment]
这个是个bug,可以进wx群发你一个新版

**Comment by roukaixin** [comment]
> 这个是个bug,可以进wx群发你一个新版

群二维码已过期，我使用的是linux,所以我等发版吧

**Comment by houxinlin** [comment]
好的，发版我会在这里通知

**Comment by roukaixin** [comment]
可以更新一个群二维码

**Comment by houxinlin** [comment]
已更新

**Comment by houxinlin** [comment]
问题已经修复，新版已发布，可到IDEA仓库升级
