### ISSUE TITLE
返回值中 = 会被转义称 unicode 编码

### ISSUE THREAD

**Issue by roukaixin** [houxinlin/cool-request#36]
![等号](https://github.com/houxinlin/cool-request/assets/47386021/a8acdd92-5a56-4687-8102-c7cb2c187b94)

可能是使用了 gson 的原因

**Comment by houxinlin** [comment]
好的，我修复一下

**Comment by roukaixin** [comment]
> 好的，我修复一下

幸苦了

**Comment by lexiaobei** [comment]
＜符号也是

**Comment by houxinlin** [comment]
> ＜符号也是

这是因为被gson美化json的时候转义了，注意进群，发你最新版

**Comment by houxinlin** [comment]
新版已经发布
