### ISSUE TITLE
静态变量url无法识别

### ISSUE THREAD

**Issue by YiMoWanXia** [houxinlin/cool-request#37]
url携带静态字符无法识别全路径，如图：
![image](https://github.com/houxinlin/cool-request/assets/53363856/4de1f61d-388b-4fcf-aa56-f24273e97174)

**Comment by houxinlin** [comment]
这种常量拼接的暂时还不支持，单独常量应该是可以的

**Comment by houxinlin** [comment]
可以自定义一个环境临时解决一下

**Comment by YiMoWanXia** [comment]
好的

**Comment by houxinlin** [comment]
问题已经修复，新版已发布，可到IDEA仓库升级
