### ISSUE TITLE
建议增加接口的中文显示

### ISSUE THREAD

**Issue by cheng896911036** [houxinlin/cool-request#41]
建议能够根据接口的中文注释增加每个接口的中文名称，这样对于小型公司、个人全栈开发比较有用。接口能够一目了然，不需要再找swagger等再重新对应接口。

**Comment by houxinlin** [comment]
这个是下个版本优化的方向，喜欢的话点个star

**Comment by cheng896911036** [comment]
> 这是下个版本优化的方向，喜欢的话点个star

可以试试自定义注解，或者通过swagger注解等方式，期待大神的杰作。

**Comment by houxinlin** [comment]
新版已经增加，可通过配置swagger实现
