### ISSUE TITLE
关于启动之后的刷新api消失的问题

### ISSUE THREAD

**Issue by typvip** [houxinlin/cool-request#47]
首先肯定大大的这个插件十分友好，真的特别nice，超级喜欢，希望越来越好、做大做强！！！
插件目前的工作逻辑是在启动的时候读取容器加载api列表，但实际操作的时候有时候会无意点到刷新按钮，这个时候api列表就会消失，需要重新启动项目才能继续工作，希望这点可以优化一下。
思路：建议刷新可以从RequestMappingHandlerMapping这个类入手，可以获取到所有构建的api列表。
![image](https://github.com/houxinlin/cool-request/assets/89885784/be811ffb-0102-4e0d-95dd-3fb96ef7b018)

**Comment by houxinlin** [comment]
首先启动后确实是从RequestMappingHandlerMapping中获取的，点击刷新按钮，是静态扫描，可能扫描不全，其中不包括第三方jar中的，扫描按钮会先删除所有的数据，所以从RequestMappingHandlerMapping中获取的数据也会被删除，这方面确实需要优化，但是不要点刷新就好了

**Comment by typvip** [comment]
好的，谢谢，大大加油  ^~^

**Comment by houxinlin** [comment]
新已解决
