### ISSUE TITLE
导出openapi报错空指针

### ISSUE THREAD

**Issue by zyk1994** [houxinlin/cool-request#48]
OpenApiUtils
249行methodDescription为null
256行空指针

**Comment by houxinlin** [comment]
好的，下个版本解决，主要是没有解析到swagger的注解

**Comment by zyk1994** [comment]
> 好的，下个版本解决，主要是没有解析到swagger的注解

辛苦大佬🥳

**Comment by houxinlin** [comment]
新版已解决
