### ISSUE TITLE
本地环境none无法配置全局请求头参数

### ISSUE THREAD

**Issue by xuguoqin** [houxinlin/cool-request#49]
我在本地环境none的时候需要使用到一些通用的全局header，并且期望在不同的环境里面也使用相同的header，目前不仅不支持所有环境通用的header，而且本地环境也无法设置通用header

**Comment by houxinlin** [comment]
在多个环境设置同样的header吧

**Comment by xuguoqin** [comment]
就是我这个header里面可能会有用户Id这种参数，需要经常改，换环境每次都要修改，然后你这个本地好像也不支持设置全局header这里对使用也比较麻烦

**Comment by houxinlin** [comment]
加下群，主页，进群讨论下
