### ISSUE TITLE
程序没有正常结束

### ISSUE THREAD

**Issue by Susuper2019** [houxinlin/cool-request#51]
![image](https://github.com/houxinlin/cool-request/assets/53945022/f11298ba-6e55-49d1-a855-a8b006f7ea15)
程序结束后，无法正常退出jvm，线程堆栈信息如下。IDEA版本是IntelliJ IDEA 2024.1 (Ultimate Edition)
[新文件 5.txt](https://github.com/houxinlin/cool-request/files/15103784/5.txt)

**Comment by houxinlin** [comment]
这是个bug，升级到v2024.4.15就可以解决
