### ISSUE TITLE
使用问题报告

### ISSUE THREAD

**Issue by jiushihenni** [houxinlin/cool-request#53]
1.启用动态刷新和方法跟踪后,普通的main方法主线程走完后程序无法退出,会一直处于活动状态.
2.调用接口时间很长,调用步骤太久,有时候会直接无法走通,可能是for循环无法退出,效率上远不如postman

**Comment by houxinlin** [comment]
1. 第一点是个bug，在新版已经修复
2. 启用方法跟踪后，在发起http请求后，首先会进行一系列得方法分析，会拖慢请求速度，禁用就好
3. 调用接口时间很长，先分析一下自己网络问题，还有自己接口问题
4. 不满意可以卸载
