### ISSUE TITLE
批量复制http url优化

### ISSUE THREAD

**Issue by yanbo988** [houxinlin/cool-request#54]
在一个controller目录下选择多个路径，右击点复制 http url
<img width="626" alt="image" src="https://github.com/houxinlin/cool-request/assets/23182626/3960879e-57bd-44e3-ac44-ab2a23de6b9e">

结果点粘贴的时候要么显示的不对，要么什么也复制的结果是空
只有选择单个的时候，可以正常复制

**Comment by houxinlin** [comment]
只支持单个复制，批量复制下个版本可以支持一下
