### ISSUE TITLE
GET请求参数传递有点问题

### ISSUE THREAD

**Issue by yanbo988** [houxinlin/cool-request#55]
用get方式请求接口传参
appChannel=ios
但是dubug调试的时候，发现实际接收值变成"ios,"多了一个逗号
![image](https://github.com/houxinlin/cool-request/assets/23182626/7344bfc0-9459-4ed8-b696-e26f256b6313)

**Comment by houxinlin** [comment]
我在最新得版本(5.1)上测试了，不存在这个问题。
首先检查一下配置，看看是不是多写了appChannel，只有当配置多个appChannel时候，SpringBoot在获取时候才有逗号分割

**Comment by yanbo988** [comment]
![image](https://github.com/houxinlin/cool-request/assets/23182626/1a14ebae-754c-48de-a847-7d7557667c5f)
这是完整的请求，没有多写appChannel

**Comment by yanbo988** [comment]
我用的也是5.1版本，我是mac电脑，这个问题确实挺奇怪，我用postman请求时，就没有多余的逗号

**Comment by houxinlin** [comment]
检查Query参数表格
![image](https://github.com/houxinlin/cool-request/assets/38684327/7ff23c49-6a38-4c10-aa20-14dc38e161f0)
