### ISSUE TITLE
trace功能失效啦

### ISSUE THREAD

**Issue by chenjing-pacvue** [houxinlin/cool-request#56]
trace功能失效啦
idea版本2024.01.01
![image](https://github.com/houxinlin/cool-request/assets/169041926/713bd55b-c8bc-4249-8938-e0e6ba9e2d8b)
![image](https://github.com/houxinlin/cool-request/assets/169041926/575b07aa-6fc2-4d10-a04d-9c942fa34796)

**Comment by houxinlin** [comment]
是突然失效还是一直没有成功过，主页进群沟通下

**Comment by oklimu** [comment]
俺也一样，没有成功过

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载
