### ISSUE TITLE
[Feature]可否增加MQ的调用

### ISSUE THREAD

**Issue by anjia0532** [houxinlin/cool-request#57]
目前已有 [手动触发定时器](https://coolrequest.dev/docs/tutorial-basics/request_timer) 和 [手动触XXL-JOB任务](https://coolrequest.dev/docs/tutorial-basics/request_xxljob)

以RabbitMQ为例，可以通过 `org.springframework.amqp.rabbit.annotation.RabbitListener` 注解监听消息。

目前我是通过 [Arthas-vmtool](https://arthas.aliyun.com/doc/vmtool.html) 和 [arthas idea plugin 使用文档 - 6、更高级获取实例 vmtool](https://www.yuque.com/arthas-idea-plugin/help/pe6i45#OVCdl) 来手动调用的

**Comment by houxinlin** [comment]
这些正在安排

**Comment by anjia0532** [comment]
现在新版的 `Call this Method` 已经满足使用了，感谢。
![image](https://github.com/houxinlin/cool-request/assets/15098916/7dd3bcf9-0e1a-473b-a7bb-19e6c69dd6a9)
