### ISSUE TITLE
纯属好奇，这个插件更牛逼在哪

### ISSUE THREAD

**Issue by newhoo** [houxinlin/cool-request#58]
看了下特性和源码，不太理解这个插件牛逼在哪

**Comment by newhoo** [comment]
1、用java做脚本不是个好主意，太局限了，用js脚本更通用
2、反射请求(包括调度器) 这块做的太复杂了，功能应该还不够用。倒不如看下这个插件[bean-invoker](https://github.com/newhoo/bean-invoker)，原理简单，运行中随时调用spring bean，一般配合jrebel使用，当然可能还有更好实现
3、Trace方法耗时统计，没看到详细描述

**Comment by houxinlin** [comment]
1. 按道理使用我的插件的用户都是100%使用java的，在java脚本里，可以调用任意第三方库，或者项目自己class中的方法，在或者是更接近底层的操作，甚至可以创建窗口、创建socket,如果你想的话，没太理解太局限是什么意思，也不可能所有的用户都会js把。
2. 反射请求，确实是复杂，但是在请求参数转换上，比如HttpServletRequest，Part这些参数通过bean-invoker可以传递吗？，还有响应结果预览。
3. Trace可以看下这个介绍 https://coolrequest.dev/docs/tutorial-basics/trace

**Comment by newhoo** [comment]
> 1. 按道理使用我的插件的用户都是100%使用java的，在java脚本里，可以调用任意第三方库，或者项目自己class中的方法，在或者是更接近底层的操作，甚至可以创建窗口、创建socket,如果你想的话，没太理解太局限是什么意思，也不可能所有的用户都会js把。
> 2. 反射请求，确实是复杂，但是在请求参数转换上，比如HttpServletRequest，Part这些参数通过bean-invoker可以传递吗？，还有响应结果预览。
> 3. Trace可以看下这个介绍 https://coolrequest.dev/docs/tutorial-basics/trace

1、太局限就用这句话解释`按道理使用我的插件的用户都是100%使用java的`，当然定位不一样。java js引擎还是很强大的，[Nashorn —— Java 8 JavaScript 引擎](https://mouse0w0.github.io/2018/12/02/Introduction-to-Nashorn/)
2、回到原点，模拟http请求直接用http工具发起就好了
3、整个trace思路还不错，就是本地开发用这个感觉意义不大

其他不言了，有时间折腾还是不错的

**Comment by houxinlin** [comment]
我觉得你还是没理解反射请求的意义
