### ISSUE TITLE
反射调用失败

### ISSUE THREAD

**Issue by DazeCake** [houxinlin/cool-request#60]
http调用正常，但是反射调用失败
```
java.rmi.ConnectException: Connection refused to host: 198.18.1.147; nested exception is: 
	java.net.ConnectException: Operation timed out
```

顺带一提，插件设计的太好了，极大的解决了开发时候反复切换窗口和找请求接口的心智负担，支持

**Comment by houxinlin** [comment]
谢谢，这个错还没有遇到过，反射请求时候需要连接一个rmi服务，至于为什么连接不上，还得排查一下，但是我写死的是localhost，因为是本地的服务，你这里为什么出现198.18.1.147呢，方便进去排查一下吗

**Comment by DazeCake** [comment]
好的 我猜测可能是我这边的网络环境问题，因为在公司经常会来回切换clash和vpn

**Comment by DazeCake** [comment]
已申请qq群
