### ISSUE TITLE
关于Call方法的问题

### ISSUE THREAD

**Issue by alsc1n** [houxinlin/cool-request#64]
目前已知运行单个项目的时候此功能可以正常运行,但是遇到多个项目同时启动的时候,Call方法不可用.以下为两个同时运行的项目,不同的方法执行Call的结果,只有一个可用
<img width="623" alt="PixPin_2024-06-25_18-59-16" src="https://github.com/houxinlin/cool-request/assets/57469397/1f52219d-ecba-4a12-ab50-184f9cf51763">
<img width="620" alt="PixPin_2024-06-25_18-58-56" src="https://github.com/houxinlin/cool-request/assets/57469397/f26b5d9a-e145-4546-9d22-bc9758968402">

**Comment by houxinlin** [comment]
确实存在这个问题，等待下个版本优化

**Comment by ok123zxx** [comment]
> 目前已知运行单个项目的时候此功能可以正常运行,但是遇到多个项目同时启动的时候,Call方法不可用.以下为两个同时运行的项目,不同的方法执行Call的结果,只有一个可用 <img alt="PixPin_2024-06-25_18-59-16" width="623" src="https://private-user-images.githubusercontent.com/57469397/342699606-1f52219d-ecba-4a12-ab50-184f9cf51763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjIwMzIsIm5iZiI6MTcxOTkyMTczMiwicGF0aCI6Ii81NzQ2OTM5Ny8zNDI2OTk2MDYtMWY1MjIxOWQtZWNiYS00YTEyLWFiNTAtMTg0ZjljZjUxNzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTNmNmZiZWU3MjI5ZGE2YmFiNzI0N2MzMmU1ZDhlZjZiMTdlMDM3NjQ1M2QwODgxMTdkZGVhYTg5YTkzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ubUJb91MWOS8fnUndt_PYrclQwIcSVhIaxfIE2DVm4"> <img alt="PixPin_2024-06-25_18-58-56" width="620" src="https://private-user-images.githubusercontent.com/57469397/342699613-f26b5d9a-e145-4546-9d22-bc9758968402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjIwMzIsIm5iZiI6MTcxOTkyMTczMiwicGF0aCI6Ii81NzQ2OTM5Ny8zNDI2OTk2MTMtZjI2YjVkOWEtZTE0NS00NTQ2LTlkMjItYmM5NzU4OTY4NDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEyMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTZmMThkMTk5M2EwYTdkNTAxYmVjYTA2YjhkZDVmNjY2NzExMTE2M2I4NzUxNzY3ODExZWI3MzBhYThhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MspQYjf5KPWok_8wPIMMu_2FympjSJV00eN-3-BApDQ">

老哥你是广州云徙的吗

**Comment by houxinlin** [comment]
新版本已经修复
