### ISSUE TITLE
关于返回结果转义显示

### ISSUE THREAD

**Issue by lgg476864889** [houxinlin/cool-request#65]
使用cool请求时得到的返回结果在json结果栏显示时把=号转义了
如：
cool返回
https://xxxx?sign\u003dq-sign-algorithm%3Dsha1%26q-ak%3DAKID17CBB4lFbkkU6VxHTYTEpFTJD3f9g9RV%26q
正常返回应该是：sign=q-sign, postman,浏览器都是返回如下
https://xxxx?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKID17CBB4lFbkkU6VxHTYTEpFTJD3f9g9RV%26q

因为这个是有加密信息的，导致一直验证不通过，我还以为写错了

**Comment by houxinlin** [comment]
这个错误已经修复了,现在是哪个版本？ 用2024.7.1试试

https://github.com/houxinlin/cool-request/issues/36

**Comment by lgg476864889** [comment]
2024.7.1版本已解决，辛苦了
