### ISSUE TITLE
Api视图展示优化，文件夹展开支持合并，减少层级

### ISSUE THREAD

**Issue by warmchuang** [houxinlin/cool-request#68]

**Comment by warmchuang** [comment]
![1](https://github.com/user-attachments/assets/753bd24c-8a20-4853-8ae2-9cda8502ae44)
![2](https://github.com/user-attachments/assets/c6d2929a-c084-4232-8ecd-084ea5b55acd)

**Comment by houxinlin** [comment]
有道理

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载
