### ISSUE TITLE
是否可以调用任意API

### ISSUE THREAD

**Issue by Susuper2019** [houxinlin/cool-request#7]
![image](https://github.com/houxinlin/cool-request/assets/53945022/8432931b-b66a-4628-9bfd-cce0f6c7ddc6)
访问百度接口，提示select a node，是否支持这样使用

**Comment by houxinlin** [comment]
> ![image](https://private-user-images.githubusercontent.com/53945022/306934273-8432931b-b66a-4628-9bfd-cce0f6c7ddc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDE1NjAsIm5iZiI6MTcwODYwMTI2MCwicGF0aCI6Ii81Mzk0NTAyMi8zMDY5MzQyNzMtODQzMjkzMWItYjY2YS00NjI4LTliZmQtY2NlMGY2YzdkZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDExMjc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNDNlNDE5YTVlZTk2MWQ3NjA5ZTFmNjBhZWQyMTFhNDE4MDgwYjFiNzQzNDM5ZjI0NjEzYjJiNDc0MjI5NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svCbPkmWrYSGLDCvLtz0tLKrXj8uSn2O37Ye2Y6BwV8) 访问百度接口，提示select a node，是否支持这样使用

是的，这是设计的上一个缺陷，已经在新版本中改正，新版本预计月底发布，感谢支持

**Comment by houxinlin** [comment]
已修复
