### ISSUE TITLE
动态扫描不支持spring.mvc.servlet.path配置

### ISSUE THREAD

**Issue by riane5** [houxinlin/cool-request#75]
配置文件配置了URL的统一请求前缀，采用配置属性 spring.mvc.servlet.path ，但是动态扫描时，解析不出来正确的URL，能否支持一下

**Comment by houxinlin** [comment]
可以新建环境解决，或者主页有群，新版本也可以解决这个问题，现在支持得是server.servlet.context-path

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载

**Comment by riane5** [comment]
优秀优秀 太牛了
