### ISSUE TITLE
建议在Controller类上新增 Copy  Full URL、Copy Path、Copy as cUrl 相关的功能

### ISSUE THREAD

**Issue by MxJ24** [houxinlin/cool-request#77]
建议在Controller类上新增 Copy  Full URL、Copy Path、Copy as cUrl 相关的功能

**Comment by houxinlin** [comment]
新版本已经有了

**Comment by MxJ24** [comment]
[2024.8.1](https://plugins.jetbrains.com/plugin/23555-cool-request/versions/stable/581326)

**Comment by MxJ24** [comment]
我等正式版吧，多谢

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载

**Comment by peng051410** [comment]
> 下个版本，可以进群发你新版，群二维码在主页有， ![image](https://private-user-images.githubusercontent.com/38684327/354984766-c5ddb40e-8591-494f-9a90-577414a8b439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTA2ODQsIm5iZiI6MTcyOTA1MDM4NCwicGF0aCI6Ii8zODY4NDMyNy8zNTQ5ODQ3NjYtYzVkZGI0MGUtODU5MS00OTRmLTlhOTAtNTc3NDE0YThiNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAzNDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OWU2MjVjMzRjMmZkODQ4NDExZTBiZWIxOWQ0ZWJmZmNmNTc1MjM2NzA0Y2IzYTY5M2UwZGMwMzVmMDdjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1x7ecEFR5j0Mqfd3NRXuD8nlOOOn3yz0uSGYKRUNOac)

可以把这些操作加到代码右键菜单上吗？可以在idea action 中进行调用，类似 RestfulTool 插件那样，它提供了RestfulTool.action.OptionForEditor-CopyApiPath action

**Comment by houxinlin** [comment]
> 可以把这些操作加到代码右键菜单上吗？可以在 idea action 中进行调用，类似 RestfulTool 插件那样，它提供了RestfulTool.action.OptionForEditor-CopyApiPath action

想要快捷键？
