### ISSUE TITLE
无法正确解析出请求体的content-type

### ISSUE THREAD

**Issue by riane5** [houxinlin/cool-request#78]
1、接口定义
![image](https://github.com/user-attachments/assets/bf7454c9-f221-4fcd-b9f2-cc0c30a56a30)
2、接口实现
![image](https://github.com/user-attachments/assets/a0b856c7-4e37-4f92-9674-5e10d3a8465e)

3、点击左边的coolrequest的小按钮生成请求时，结果content-type变更了urlencoded格式的，json体为空（不管是在controller层点击还是api接口层点击，都是一样的错误）
![image](https://github.com/user-attachments/assets/4a9273a7-049f-4e3e-bce2-9618dd8a1033)

![image](https://github.com/user-attachments/assets/46ba6dd8-1179-4f17-a3d9-5967ac33443e)

4、之前使用的是2024.2.20这个版本是正确的，最近更新新版本之后变得有问题了

**Comment by houxinlin** [comment]
这个是个问题，新版已经修复了，等下个版本或者主页进群内测

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载

**Comment by riane5** [comment]
优秀优秀，点赞
