### ISSUE TITLE
静态资源服务器功能

### ISSUE THREAD

**Issue by yanbo988** [houxinlin/cool-request#8]
我开启了静态资源服务功能，但是在浏览器访问不了文件
![image](https://github.com/houxinlin/cool-request/assets/23182626/fe20cab0-4b92-4561-b303-360be4c143be)
![image](https://github.com/houxinlin/cool-request/assets/23182626/d9a6dfb6-05cd-4cc3-a177-a4ab4d9015f4)
请问是我哪里配置不对吗

**Comment by houxinlin** [comment]
> 我开启了静态资源服务功能，但是在浏览器访问不了文件 ![image](https://private-user-images.githubusercontent.com/23182626/307241430-fe20cab0-4b92-4561-b303-360be4c143be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODA4ODMsIm5iZiI6MTcwODY4MDU4MywicGF0aCI6Ii8yMzE4MjYyNi8zMDcyNDE0MzAtZmUyMGNhYjAtNGI5Mi00NTYxLWIzMDMtMzYwYmU0YzE0M2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5Mjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDk5ODEzNjM3NjQ5MDRmNjg4NjIyYjYwOWNmOWJmMzE1YjFiNzk4YmNjMmRkZjA0YTFkZjQyMjJmMzkyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L1MuKELzQgzp3v3OPM_Y5G7RlxbS5f2V4DyDAS8p7To) ![image](https://private-user-images.githubusercontent.com/23182626/307241610-d9a6dfb6-05cd-4cc3-a177-a4ab4d9015f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODA4ODMsIm5iZiI6MTcwODY4MDU4MywicGF0aCI6Ii8yMzE4MjYyNi8zMDcyNDE2MTAtZDlhNmRmYjYtMDVjZC00Y2MzLWExNzctYTRhYjRkOTAxNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5Mjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZjFmYTIxYzJlY2RlNzBkNDUzZWY4ZjQzMzA4NWU3M2U4YzFhYjEzYWNmODlkYzI5NmM5NzYyNDVmMGUxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VeV_VMhP_b7WoT2Nsj_d4a3lfMyW3Gaaf3jo7fyhJ64) 请问是我哪里配置不对吗

您好，目前这个问题已经发现，是mac文件权限导致，新版本已经修复，预计月底可以发布

**Comment by houxinlin** [comment]
新版已经修复
