### ISSUE TITLE
Trace 失效

### ISSUE THREAD

**Issue by fingercoder** [houxinlin/cool-request#82]
![image](https://github.com/user-attachments/assets/5e57511c-8253-44a9-af2d-24aa17adfd8b)
Idea版本：2024.1.4
已经购买会员

**Comment by houxinlin** [comment]
重启下idea试试，实在不行加我，给你调试一下

**Comment by fingercoder** [comment]
> 重启下idea试试，实在不行加我，给你调试一下

交流群有两百人的限制，没法加入

**Comment by houxinlin** [comment]
插件里有我二维码
![image](https://github.com/user-attachments/assets/08e1e9af-838b-411d-82f3-c287be16a542)

**Comment by houxinlin** [comment]
新版本发布，可在仓库下载
