### ISSUE TITLE
无法正确解析出方法的注释信息

### ISSUE THREAD

**Issue by riane5** [houxinlin/cool-request#88]
当接口方法的注释写在父类接口上时，子类继承的方法上没有注释时，无法正确解析出方法的注释

![image](https://github.com/user-attachments/assets/4c096a80-be85-42e5-8011-71e205ea08ff)

![image](https://github.com/user-attachments/assets/96843dd9-cef1-48b0-9294-365fbf6ae5f3)

![image](https://github.com/user-attachments/assets/3563ef60-be15-43d0-9ecd-d2c34053fbdb)

**Comment by houxinlin** [comment]
新版已修复
