### ISSUE TITLE
如何把一个接口返回的结果设置为全局变量值

### ISSUE THREAD

**Issue by jbasttdi** [houxinlin/cool-request#9]
你好，感谢提供这样的一个好用的插件，想问一下，我想实现全局token设置，就是先提交一个login接口，再把login接口返回的token值保存到本地cool request的全局变量值中，再在所有请求的api接口中自动把这个token设置到每个请求的header中，请问如何实现，postman可以实现的。

**Comment by houxinlin** [comment]
> 你好，感谢提供这样的一个好用的插件，想问一下，我想实现全局token设置，就是先提交一个login接口，再把login接口返回的token值保存到本地cool request的全局变量值中，再在所有请求的api接口中自动把这个token设置到每个请求的header中，请问如何实现，postman可以实现的。

可以设置环境，https://plugin.houxinlin.com/docs/tutorial-basics/env_config /，在请求发起界面左上角有个设置图标，可以配置全局请求头

**Comment by jbasttdi** [comment]
你好，你想动态设置这个Global header中的值，这个要设置的值通过接口返回。
<img width="632" alt="image" src="https://github.com/houxinlin/cool-request/assets/4523109/4a2aac7c-d58b-439c-a2aa-1455ecba4a07">

**Comment by houxinlin** [comment]
问题已经修复，新版已发布，可到IDEA仓库升级
