### ISSUE TITLE
支持 rose 框架

### ISSUE THREAD

**Issue by kevinwang0224** [houxinlin/cool-request#90]
我们项目上在用一个比较老的框架 rose 框架 ，想在作者的插件上支持一下，是否考虑？

考虑支持的话，我可以提个 pr 尝试支持一下。

**Comment by houxinlin** [comment]
还没有听过呢，我看看复不复杂，开源得这个版本已经不更新了，暂时没法pr

**Comment by kevinwang0224** [comment]
> 应该是不复杂的。我后续提交个 pr ，你看下吧。

pr 已提交。有空你可以 review 一下。 @houxinlin

**Comment by houxinlin** [comment]
这周会抽空合并

**Comment by houxinlin** [comment]
是否有Rose demo项目可提供测试

**Comment by kevinwang0224** [comment]
> 是否有Rose demo项目可提供测试

没有。 我这边测试验证是 ok 的

**Comment by kevinwang0224** [comment]
我看到已经合并 pr 了。预计什么时候会发新版本呢？

**Comment by houxinlin** [comment]
下月初
